image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
    docker pull thyrlian/android-sdk
  init: >
    flutter upgrade && 
    flutter update-packages --force-upgrade
ports:
- port: 8080
  onOpen: open-preview
vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
