image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addBadge: true
    addLabel: Open in Gitpod
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter upgrade &&
    flutter update-packages --force-upgrade &&
    flutter doctor --android-licenses &&
    # sdkmanager "platforms;android-30" "build-tools;30.0.2" "system-images;android-30;google_apis;x86_64" &&
    # yes "" | avdmanager -s create avd --name pixel -k "system-images;android-30;google_apis;x86_64"
ports:
- port: 8080
  onOpen: open-preview
vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
