image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addBadge: true
    addLabel: Open in Gitpod
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter upgrade && 
    flutter update-packages --force-upgrade &&
ports:
- port: 8080
  onOpen: open-preview
vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
