name: scibble
description: A tool for scanning products into the Online kiosk
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1        # Asynchronous state management
  http: ^0.13.3               # Send/recieve HTTP requests
  webview_flutter: ^3.0.0     # In-app web browser for authorization
  crypto: ^3.0.1              # Generate hashes for authentication
  shared_preferences: ^2.0.8  # Store/load app settings natively
  flutter_dotenv: ^5.0.2      # Hide secrets when developing

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - .env
  uses-material-design: true