name: flutter-actions
on: [pull_request]
jobs:
  flutter-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1.4.0
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Test code
        run: flutter test --coverage
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: coverage/example.lcov
          min_coverage: 90
          token: ${{secrets.GITHUB_TOKEN}}
