name: flutter-actions
on: [push, pull_request]
jobs:
  prepare-flutter:
    - name: install dependencies
      uses: steebchen/flutter@v1.1.0
      with:
        args: pub get

  run-tests:
    steps:
      - run: flutter tests --coverage
