name: flutter-actions
on: [pull_request_target, pull_request]
jobs:
  build:
    name: Build and test project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Add secrets to .env
        run: echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" > .env
      - name: Test code
        run: flutter test --coverage
      - name: Show coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@v1.1.2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: ./coverage/lcov.info
